apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: foo-ingress
spec:
  rules:
  - host: app.trackswiftly.com
    http:
      paths:
      - path: /
        pathType: Exact
        backend:
          service:
            name: fast-api-service
            port:
              number: 80
