# apiVersion: metallb.io/v1beta1
# kind: IPAddressPool
# metadata:
#   name: my-ip-pool
#   namespace: trackswiftly
# spec:
#   addresses:
#     - 161.35.71.46-165.232.122.31  # Replace with a range of free IPs in your network
# ---
# apiVersion: metallb.io/v1beta1
# kind: L2Advertisement
# metadata:
#   name: my-l2-advertisement
#   namespace: trackswiftly
# spec:
#   ipAddressPools:
#     - my-ip-pool




# The address-pools lists the IP addresses that MetalLB is
# allowed to allocate. You can have as many
# address pools as you want.
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  # A name for the address pool. Services can request allocation
  # from a specific address pool using this name.
  name: first-pool
  namespace: trackswiftly
spec:
  # A list of IP address ranges over which MetalLB has
  # authority. You can list multiple ranges in a single pool, they
  # will all share the same settings. Each range can be either a
  # CIDR prefix, or an explicit start-end range of IPs.
  addresses:
  - 165.232.122.31-165.232.122.31
