apiVersion: v1
kind: Service
metadata:
  name: {{ include "trackswiftly-user-chart.fullname" . }}
  labels:
    # {{- include "trackswiftly-user-chart.labels" . | nindent 4 }}
    app: trackswiftly-user-chart 
spec:
  selector:
    app: trackswiftly-user-chart

  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http